[package]
name = "stdcpp-linkage-mre"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[[bin]]
name = "test_mylib"
path = "src/main.rs"

[build-dependencies]
cmake = "0.1.44"
